// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LocacaoDeVeiculos.DATA.Models
{
    [Table("Cliente_Veiculo")]
    public partial class ClienteVeiculo
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idVeiculo")]
        public int IdVeiculo { get; set; }
        [Column("idCliente")]
        public int IdCliente { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataEmprestimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataEntrega { get; set; }
        public bool? Entrega { get; set; }

        [ForeignKey("Id")]
        [InverseProperty("ClienteVeiculo")]
        public virtual Veiculo Id1 { get; set; }
        [ForeignKey("Id")]
        [InverseProperty("ClienteVeiculo")]
        public virtual Cliente IdNavigation { get; set; }
    }
}