// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LocacaoDeVeiculos.DATA.Models
{
    public partial class Veiculo
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Modelo { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Marca { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Ano { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Tipo { get; set; }

        [InverseProperty("Id1")]
        public virtual ClienteVeiculo ClienteVeiculo { get; set; }
    }
}