// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LocacaoDeVeiculos.DATA.Models
{
    [Keyless]
    public partial class VwVeiculoCliente
    {
        [Required]
        [Column("CPF")]
        [StringLength(14)]
        [Unicode(false)]
        public string Cpf { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Marca { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Modelo { get; set; }
        [Column("id")]
        public int Id { get; set; }
        [Column("idVeiculo")]
        public int IdVeiculo { get; set; }
        [Column("idCliente")]
        public int IdCliente { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataEmprestimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataEntrega { get; set; }
        public bool? Entrega { get; set; }
    }
}